name: Java CI

on:
  push:
    branch: ["main"]
  pull_request:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print to console
        run: echo Hello GH Actions
